name: Update Snapshot Tag

permissions:
  id-token: write
  contents: read
  packages: write

on:
  workflow_dispatch:

jobs:
  copy-tag:
    runs-on: depot-ubuntu-22.04

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup crane
        uses: imjasonh/setup-crane@v0.5

      - name: Copy to oss snapshot tag
        run: |
          # Support both main and master branches
          if crane manifest ghcr.io/${{ github.repository }}:main > /dev/null 2>&1; then
            crane tag ghcr.io/${{ github.repository }}:main main-$(date +%Y%m%d)
          fi
          if crane manifest ghcr.io/${{ github.repository }}:master > /dev/null 2>&1; then
            crane tag ghcr.io/${{ github.repository }}:master master-$(date +%Y%m%d)
          fi

      - name: Copy to enterprise snapshot tag
        run: |
          # Support both main and master branches
          if crane manifest ghcr.io/${{ github.repository }}-enterprise:main > /dev/null 2>&1; then
            crane tag ghcr.io/${{ github.repository }}-enterprise:main main-$(date +%Y%m%d)
          fi
          if crane manifest ghcr.io/${{ github.repository }}-enterprise:master > /dev/null 2>&1; then
            crane tag ghcr.io/${{ github.repository }}-enterprise:master master-$(date +%Y%m%d)
          fi
